### ISSUE TITLE
大神，发现有个bug

### ISSUE THREAD

**Issue by hevi1991** [blurryssky/BSNumbersView#1]
假如bodyData的数据能将这个NumbersView填满的话，显示没问题，但是如果填不满，最后的一行数据在向右滑动时shadow显示不出来。

**Comment by blurryssky** [comment]
谢谢你的评论，我发现并且已经修复了，你看看是不是这个问题，最新的版本是0.2.2

**Comment by hevi1991** [comment]
pod update之后 依然存在这个bug。~倒是上面那条白边不见了

**Comment by hevi1991** [comment]
回复很及时，谢谢您的贡献~

**Comment by blurryssky** [comment]
这个小问题竟然不能一次解决，我有一种深深的挫败感。你能确保tag已经是0.2.2了吗？白边是什么？你可以放点截图上来

**Comment by hevi1991** [comment]
嗯，肯定是0.2.2了，之前没更新前，headerView上面有条白色的边，找了好久，改了一下搞定了。可能我用得不对，现在没了。
![img_1](https://cloud.githubusercontent.com/assets/15024868/16226337/8ae914c0-37dd-11e6-9043-b51292f1a934.png)
![img_2](https://cloud.githubusercontent.com/assets/15024868/16226340/8c13c75a-37dd-11e6-8468-0698f28f5f9b.png)

**Comment by blurryssky** [comment]
使用 
 >pod 'BSNumbersView', '~> 0.2.2' 

然后`pod install` 试试

**Comment by hevi1991** [comment]
原来 pod装的不是最新的啊。。这个问题解决了~
但是白边出来了。
![img_1](https://cloud.githubusercontent.com/assets/15024868/16251393/27383034-3858-11e6-9cea-aca3a9957c7d.png)

**Comment by hevi1991** [comment]
不知道是不是UICollectionViewFlowLayout的问题，我改低了headerReferenceSize的Height 就不见了
![img_1](https://cloud.githubusercontent.com/assets/15024868/16251553/7b073aba-3859-11e6-8a45-c0576301428d.png)

**Comment by blurryssky** [comment]
哦 这个问题我后面再想一想
