### ISSUE TITLE
大神，后期会加入编辑功能吗？？

### ISSUE THREAD

**Issue by ganjmeng** [blurryssky/BSNumbersView#2]
大神，后期会加入编辑功能吗？？

**Comment by blurryssky** [comment]
还是别叫大神吧。。。
既然你都这么说了 有空我一定加上

**Comment by hevi1991** [comment]
= =会玩runtime都是大神啊，反正我看不懂。。

**Comment by blurryssky** [comment]
哈哈，runtime的类容并不多，也不难，熟悉cocoa后很自然就能懂了，不用特殊对待，看成一些普通的api就可以了

**Comment by blurryssky** [comment]
我想了一下 编辑的可定制性挺大的 
1你可以使用代理方法
`- (nullable UIView *)numbersView:(BSNumbersView *)numbersView
                 viewAtIndexPath:(NSIndexPath *)indexPath;`
返回`UITextField`或者`UITextView`来完成编辑功能

2或者点击的时候使用`UIAlertController`来提示修改

我会增加一个方法来刷新指定的格子数据
`- (void)reloadItemsAtIndexPaths:(NSArray<NSIndexPath *> *)indexPaths;`
