### ISSUE TITLE
第一个cell是空白的  使用navigation  push过去之后

### ISSUE THREAD

**Issue by manbu1573** [blurryssky/BSNumbersView#4]
- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath {
    BSNumbersCollectionCell *cell = [collectionView dequeueReusableCellWithReuseIdentifier:CellReuseIdentifer forIndexPath:indexPath];
    cell.horizontalMargin = self.horizontalItemTextMargin;
    if (collectionView == self.headerFreezeCollectionView) {
        [self configureHeaderFreezeCell:cell indexPath:indexPath];
    } else if (collectionView == self.headerSlideCollectionView) {
        [self configureHeaderSlideCell:cell indexPath:indexPath];
    } else if (collectionView == self.freezeCollectionView) {
        [self configureBodyFreezeCell:cell indexPath:indexPath];
    } else {
        [self configureBodySlideCell:cell indexPath:indexPath];
    }
    
    cell.separatorColor = self.verticalSeparatorColor;
    cell.separatorHidden = NO;
    NSInteger valuesCount = self.bodyData.firstObject.bs_propertyValues.count;
    if (valuesCount == self.freezeColumn) {
        if (indexPath.row == self.freezeColumn - 1) {
            cell.separatorHidden = YES;
        }
    } else {
        if (indexPath.row == valuesCount - self.freezeColumn - 1) {
            cell.separatorHidden = YES;
        }
    }
    return cell;
}
在这个方法中 if (collectionView == self.headerFreezeCollectionView) {
        [self configureHeaderFreezeCell:cell indexPath:indexPath];
    } 没有执行

**Comment by blurryssky** [comment]
要看看你写的代码才行 把你的代码贴上来吧

**Comment by blurryssky** [comment]
将 automaticallyAdjustsScrollViewInsets 设置为NO
感谢 @AlasKuNull
