### ISSUE TITLE
0行0组是空白的,还有数据怎么老是会越界?bodyData和headerData是不是有什么规定或者联系啊?

### ISSUE THREAD

**Issue by AlasKuNull** [blurryssky/BSNumbersView#5]
下面是代码,完全按照sample来弄得  只是我用的pod  因为项目用的swift. 就是会多出一列来,不多写一列就会报数组越界的错误.
/// BSNumberView 初始化

`detailView = BSNumbersView.init(frame: CGRectMake(0, 0, self.view.bounds.height, self.view.bounds.width))

        view.addSubview(detailView!)

        detailView?.snp_makeConstraints(closure: { (make) in
            make.leading.trailing.bottom.equalTo(view)
            make.top.equalTo(view).offset(32)
        })

        detailView?.freezeColumn = 1

        detailView?.slideBodyFont = UIFont.systemFontOfSize(14)

        detailView?.delegate = self

        detailView?.layer.borderWidth = 0.5

        detailView?.layer.borderColor = UIColor.lightGrayColor().CGColor`
/// 在获取数据的地方设置BSNumberView的数据
  
                   ` self.detailView?.bodyData = self.dataArray!

                    self.detailView?.headerData = self.sectionArray

                    self.detailView?.reloadData()`
代理方法我都没有实现,界面显示正常,只是最左上角那个是空白的...
然后,还有个问题就是:
dataArray.里面的模型属性个数是8个,sectionArray必须要有9个才不会崩,否则就数组越界.请帮我看看  谢谢

**Comment by AlasKuNull** [comment]
左上角空白是因为导航控制器automaticallyAdjustsScrollViewInsets这个属性,设置为false就行了.
sectionArray设置数据必须要多设置一列才不会崩,否则就会出现数组越界.  多出来的一列显示的数据是当前模型的所有内容...求解答

**Comment by blurryssky** [comment]
是的 headerData和bodyData的列数需要一致，如果headerData少了，你可以用一个空字符串""占位

发自我的 iPhone

**Comment by AlasKuNull** [comment]
谢谢你的回答,我现在的情况是   headerData的个数和bodyData里面模型属性个数是一致的,还是会出现越界的错误,只有当headerData的个数比bodyData里面的模型属性个数多1的时候才不会出现越界,但是我看了您的sample里面模型属性数目和headerData是一致也并没有报错,难道就因为一个swift  一个OC?还是因为pod的问题?

**Comment by blurryssky** [comment]
我用swift工程测试过了，代码和oc里的一样，没有发现你说的问题，我的模型是这样的
```swift
class Flight: NSObject {
    
    var company: String!
    var number: String!
    var typeOfAircraft: String!
    var date: String!
    var placeOfDeparture: String!
    var placeOfDestination: String!
    var departureTime: String!
    var arriveTime: String!
    var price: String!
    
    convenience init(dic: [String : String]){
        self.init()
        for (key, value) in dic {
            setValue(value, forKey: key)
        }
    }
}
```

ViewController里：
```swift
let flightsInfo = NSArray(contentsOfFile: NSBundle.mainBundle().pathForResource("flightsInfo", ofType: "plist")!) as! [[String : String]]
        
let flights = flightsInfo.map {
    Flight(dic: $0)
}
numbersView.bodyData = flights;
numbersView.headerData = ["Flight Company", "Flight Number", "Type Of Aircraft", "Date", "Place Of Departure", "Place Of Destination", "Departure Time", "Arrive Time", "Price"]
numbersView.freezeColumn = 1
numbersView.reloadData()
```
你检查一下是否你的模型有基类 或者别的错误？

**Comment by AlasKuNull** [comment]
谢谢你的耐心回答 我找到问题了   字典转模型的方法不一致导致我出现了这个错误  非常感谢!!!

**Comment by AlasKuNull** [comment]
谢谢耐心的回答,原来是因为我的模型里面我习惯性的增加了
`override var description:String {
        
        let keys = ["backQty","outQty","producerName","productName","productNo","quantity","specification","tempQty"]
        
        return dictionaryWithValuesForKeys(keys).description
    }`
这个字段,导致我越界的错误...
非常感谢!
另外能请教一下
let flights = flightsInfo.map {
    Flight(dic: $0)
}
这个代码的意思吗?

**Comment by blurryssky** [comment]
不谢：］ 你可以看看swift高阶函数 除了map还有filter／forEach等
