### ISSUE TITLE
大神，必须要传入一个NSObject *吗？传入一个数组怎样改呢？

### ISSUE THREAD

**Issue by duduodudu** [blurryssky/BSNumbersView#6]
从服务器上面返回的数据是数组类型，数组里面存放在数组，NSArray <NSArray *>* 该怎样解决呢？

**Comment by blurryssky** [comment]
一般从服务器取下来的数据先对其进行改造成模型，可以先把数组内的数组进行改造，存放在一个对象里

**Comment by duduodudu** [comment]
谢谢你的回答。目前现在不需要转成对象，直接展示数据即可，但是每个子数组的个数不一样，我想着就是创建一个和数组各自相同的对象来转化。也想过改动源代码来，但是还是小菜鸟。

**Comment by blurryssky** [comment]
“直接展示数据即可”意思是不需要header data吗？
“每个子数组的个数不一样”意思是每一排的个数不一样并且每列不用对齐吗？

**Comment by duduodudu** [comment]
需要展示headerData ,从不同的接口请求回来的数组的子数组不一样，直接展示不用转化成对象,可以私聊qq1431761424。

**Comment by blurryssky** [comment]
就这里说吧 别人也能看到
“不用转化成对象” 我不是很理解 我们转化成模型是为了对代码更好的管理
你意思是不同的接口返回的子数组不一样 所以不想建多个模型 如果能简单的使用数组的方式 就都可以复用一套代码了吗

**Comment by duduodudu** [comment]
我得到的数据是数组，不用转对象，按顺序直接展示、就可以了；我会按照你的建议，建立对象吧。方便以后管理。谢谢大神指点。

**Comment by blurryssky** [comment]
如果说你的很多接口返回的内容差不多 只是子数组的个数不一样 用数组直接来配置数据源 这样都复用一套代码 其实这种想法也是很合理的 毕竟代码会简洁很多 如果只是展示不做更多的操作 也不是一定要用模型。
坚持用模型的话，模型的属性不好用代码去动态添加，这个也确实比较麻烦。
解决方案：
1.每个接口建立一种模型
2.修改源代码

下来我再想一想，如果没有更好的办法，我也修改一下源代码，添加支持数组的方式。

**Comment by duduodudu** [comment]
是的，我尝试过用同一个模型去存放，结果出现小问题了。

**Comment by blurryssky** [comment]
目前还是推荐你用解决方案一吧
过段时间我准备对这个库做一点大更改，到时候再把数组的方式加进去

**Comment by duduodudu** [comment]
好的，我现在就是建立按照数组的个数建立模型的。现在是按照安卓版本APP来的，他们使用fixtableheader 。

**Comment by xuehongle** [comment]
你好，我也是根据可变的headerdata,来决定body的，所以body用的也是数组，只需要将bodydata改为数组类型，bodydata和bs_propertyValues相关的地方改为数组的处理方式就能正常显示了, 我用的swift，安卓版本我也做了，用的也是楼上说的fixtableheader，感谢作者

**Comment by blurryssky** [comment]
1.0.0支持数组了 以前那种方式也可以:]
