### ISSUE TITLE
自定义cell在ios9以下有问题

### ISSUE THREAD

**Issue by mahailin** [blurryssky/BSNumbersView#9]
修复方案：
BSNumbersView类方法dequeueReusableCellWithReuseIdentifier里的    return [collectionView dequeueReusableCellWithReuseIdentifier:identifier forIndexPath:[NSIndexPath indexPathForColumn:column inRow:row]];改为    return [collectionView dequeueReusableCellWithReuseIdentifier:identifier forIndexPath:[NSIndexPath indexPathForRow:column inSection:row]];

**Comment by blurryssky** [comment]
确实有问题, 感谢, 不过应该是[NSIndexPath indexPathForItem:column inSection:row], [NSIndexPath indexPathForRow:column inSection:row]适用于UITableView

**Comment by mahailin** [comment]
这两个应该都没问题，我用collectionview时取某个section里的某个item都是用row取，NSIndexPath里的item属性跟row属性取出来值都是一样的。

**Comment by blurryssky** [comment]
嗯 也许是苹果有优化吧
